#!/bin/bash

set -euxo pipefail

DEFAULT_CONTAINER_URL_BASE="quay.io/quobyte/pod-killer"
CONTAINER_URL_BASE="${CONTAINER_URL_BASE:-$DEFAULT_CONTAINER_URL_BASE}"
BUILD_MODE="${BUILD_MODE:-"release"}"
# buildx needs load for local testing (vs push to remote)
LOCAL_IMAGE="${LOCAL_IMAGE:-false}"

DEBUG_BINARY_DIR="./debug-binary"
APP_NAME="pod_killer"

# Enable docker containerd storage backend to build multi-arch images and load them for tests
docker info -f '{{ .DriverStatus }}' | grep "io.containerd.snapshotter.v1" > /dev/null 2>&1

container_build_and_push(){
    if [[ -z "${CONTAINER_URL_BASE}" ]]; then
      echo "FAILURE: container base url should not be empty"
    fi
    VERSION=$1
    if [[ -z "${VERSION}" || "{$VERSION}" == *\ * ]]; then
      echo "FAILURE: ${VERSION} is not a valid version string. Version must not be empty or should not contain any spaces"
    fi
    if [[ "${LOCAL_IMAGE}" = 'false' ]]; then
      git tag "${VERSION}"
      git push origin master --tags
    fi
    IMAGE="${CONTAINER_URL_BASE}:${VERSION}"
    echo "Building docker image and pushing it to ${IMAGE}"
    image_store_option="--push --output type=local,dest=${DEBUG_BINARY_DIR}"
    if [[ "${LOCAL_IMAGE}" = 'true' ]]; then
      docker buildx build --platform linux/amd64,linux/arm64 --build-arg BUILD_MODE=$BUILD_MODE \
      --build-arg APP_NAME=${APP_NAME} -t $IMAGE --load .
    else
      docker buildx build --platform linux/amd64,linux/arm64 --build-arg BUILD_MODE=$BUILD_MODE \
      --build-arg APP_NAME=${APP_NAME} -t $IMAGE --target export \
      --output type=local,dest=${DEBUG_BINARY_DIR} .
      docker buildx build --platform linux/amd64,linux/arm64 --build-arg BUILD_MODE=$BUILD_MODE \
      --build-arg APP_NAME=${APP_NAME} -t $IMAGE --push .
    fi
    push_succeeded="$?"
    if [[ ${push_succeeded} -ne 0 ]]; then
      echo 'FAILURE: container image ${IMAGE} cannot be pushed'
      echo 'Please fix the reported issues and retry'
      exit 1
    fi
}

print_usage(){
  echo './build                     Builds the executable'
  echo './build container <tag>"    Builds and pushes the container to repo'
  echo '                                         for the release'
  echo "Example: ./build container v0.1.0"
}

rm -f "${APP_NAME}.tar.gz"
rm -rf ${DEBUG_BINARY_DIR}/*

if [[ $# -eq 0 ]]; then
  docker buildx build --platform linux/amd64,linux/arm64 --build-arg BUILD_MODE=$BUILD_MODE \
    --build-arg APP_NAME=${APP_NAME} \
    --output type=local,dest=${DEBUG_BINARY_DIR} .
  if [[ "${BUILD_MODE}" = 'release' ]]; then
    echo "Debug symbols are placed under ${DEBUG_BINARY_DIR}"
  fi
  exit 0
fi

if [[ "$1" = '-h' || "$1" = '--help' ]]; then
  print_usage
else
  echo 'Building executable'
   echo "Build successful in mode: $BUILD_MODE"
  if [[ "$1" == "container" ]]; then
    container_build_and_push $2
  fi
  echo "Built binary with mode: $BUILD_MODE"
  if [[ ${LOCAL_IMAGE} == 'false' && "${BUILD_MODE}" = 'release' ]]; then
    release_tarball="${APP_NAME}.tar.gz"
    rm $release_tarball &> /dev/null || true
    tar -czf $release_tarball ${DEBUG_BINARY_DIR}
    echo
    # should be attached to release so that we can have debug symbols
    echo "IMPORTANT: Create release on source repo and attach the $release_tarball"
  fi
fi
